## NumPy Array'i Oluşturmak

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

NumPy arrayleri tek tür veri tutabilir.Eğer ilk elemanı float, diğer elemanları int girersek onları da float şeklinde saklar. Bu veri saklama maliyetini azaltır. Örneğin;

In [6]:
np.array([3.14,5,2,13])

array([ 3.14,  5.  ,  2.  , 13.  ])

Bunu bir parametre ile de ayarlayabiliriz;

In [7]:
np.array([3.14,5,2,13],dtype="int")

array([ 3,  5,  2, 13])

## Sıfırdan Array Oluşturma

In [8]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [14]:
np.random.normal(10,4,(3,4))

array([[11.17899329, 16.19509413, 10.23618582,  6.51010714],
       [ 7.68193916,  8.44343716, 12.02137833,  8.03643721],
       [12.70921409, 10.74715936,  8.93647717, 10.12213479]])

In [15]:
np.random.randint(0,10,(3,3))

array([[8, 2, 4],
       [4, 0, 2],
       [0, 6, 7]])

# Numpy Array Özellikleri

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [16]:
np.random.randint(10,size=10)

array([2, 1, 4, 0, 4, 4, 8, 9, 9, 9])

In [17]:
a = np.random.randint(10,size=10)

In [18]:
a.ndim

1

In [19]:
a.shape

(10,)

In [20]:
a.size

10

In [21]:
a.dtype

dtype('int32')

In [22]:
b = np.random.randint(10,size=(3,5))

In [23]:
b

array([[4, 2, 2, 6, 3],
       [9, 5, 1, 9, 5],
       [4, 8, 8, 1, 2]])

In [25]:
b.ndim

2

In [26]:
b.shape

(3, 5)

In [27]:
b.size

15

In [28]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme (reshaping)

In [29]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a.ndim

1

In [37]:
b = a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [38]:
b.ndim

2

**b**, **a** arrayinin iki boyutluya çevrilmiş halidir.

## Array Birleştirme (Concatenation)

In [39]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [42]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [41]:
z = np.array([7,8,9])

In [43]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a = np.array([[1,2,3],
             [4,5,6]])

In [46]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [51]:
x = np.array([1,2,3,99,99,3,2,1])

In [52]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [54]:
a,b,c = np.split(x,[3,5])
a

array([1, 2, 3])

In [55]:
b

array([99, 99])

In [56]:
c

array([3, 2, 1])

## İki boyutlu ayırma

In [57]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [59]:
ust, alt = np.vsplit(m,[2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
sag, sol = np.hsplit(m, [2])
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [64]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Sıralama

In [65]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [66]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [67]:
v

array([2, 1, 4, 3, 5])

In [68]:
v.sort()

In [69]:
v

array([1, 2, 3, 4, 5])

**sort()** metodu numpy kütüphanesinden çağırıldığı zaman veri setinin orijinal yapısını bozmaz.

## İki boyutlu array sıralama

In [70]:
m = np.random.normal(20,5,(3,3))
m

array([[15.15389961, 20.45646248, 27.57096993],
       [24.95525174, 25.1703057 , 20.15885575],
       [19.68106869, 22.17620026, 23.02725413]])

In [71]:
 np.sort(m,axis=1) #satır

array([[15.15389961, 20.45646248, 27.57096993],
       [20.15885575, 24.95525174, 25.1703057 ],
       [19.68106869, 22.17620026, 23.02725413]])

In [72]:
np.sort(m,axis=0) #sütun

array([[15.15389961, 20.45646248, 20.15885575],
       [19.68106869, 22.17620026, 23.02725413],
       [24.95525174, 25.1703057 , 27.57096993]])

## İndex ile elemanlara erişmek

In [73]:
a = np.random.randint(10,size=10)
a

array([5, 1, 6, 3, 5, 8, 8, 9, 0, 9])

In [74]:
a[0]

5

In [75]:
a[-1]

9

In [76]:
a[0]=100
a

array([100,   1,   6,   3,   5,   8,   8,   9,   0,   9])

In [77]:
m = np.random.randint(10,size = (3,5))
m

array([[0, 8, 6, 6, 4],
       [3, 1, 3, 1, 3],
       [5, 3, 2, 8, 6]])

In [78]:
m[0][0]

0

In [80]:
m[1][4]

3

In [81]:
m[1,4]

3

In [82]:
m[1,4] = 2.2
m

array([[0, 8, 6, 6, 4],
       [3, 1, 3, 1, 2],
       [5, 3, 2, 8, 6]])

Başta belirlenmiş tipi int olduğundan dolayı float eklemeye çalıştığımız zaman ondalıklı kısmını çıkartarak array'e int olarak ekler.

## Array Alt Küme İşlemleri (slicing)

In [83]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [84]:
a[0:3]

array([20, 21, 22])

In [85]:
a[:3]

array([20, 21, 22])

In [86]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [87]:
a[1::2]

array([21, 23, 25, 27, 29])

## İki boyutlu Slice işlemleri

In [88]:
m = np.random.randint(10,size=(5,5))
m

array([[7, 8, 4, 7, 3],
       [8, 9, 6, 4, 1],
       [8, 9, 9, 0, 2],
       [8, 6, 5, 4, 3],
       [0, 9, 7, 3, 2]])

In [89]:
m[:,0]

array([7, 8, 8, 8, 0])

In [90]:
m[2,:]

array([8, 9, 9, 0, 2])

In [91]:
m[0:2,0:3]

array([[7, 8, 4],
       [8, 9, 6]])

In [92]:
m[:,:2]

array([[7, 8],
       [8, 9],
       [8, 9],
       [8, 6],
       [0, 9]])

## Alt küme üzerinde işlem yapma

In [93]:
a = np.random.randint(10,size=(5,5))
a

array([[2, 0, 3, 5, 3],
       [2, 1, 7, 2, 3],
       [1, 7, 8, 0, 6],
       [4, 5, 8, 2, 2],
       [5, 2, 9, 8, 1]])

In [94]:
alt_a = a[:3,:2]
alt_a

array([[2, 0],
       [2, 1],
       [1, 7]])

In [95]:
alt_a[0,0] = 99999
alt_a[1,1] = 888
alt_a

array([[99999,     0],
       [    2,   888],
       [    1,     7]])

In [102]:
a

array([[99999,     0,     3,     5,     3],
       [    2,   888,     7,     2,     3],
       [    1,     7,     8,     0,     6],
       [    4,     5,     8,     2,     2],
       [    5,     2,     9,     8,     1]])

Görüldüğü gibi **a** veri setinin alt kümesi olan **alt_a** üzerinde yapılan değişiklik **a** veri setini de etkiledi. Bu bazen işe yarar bir özellik olsa da bazen istenmeyen bir durum olabiliyor. 
Bunun için **copy()** metodu kullanılarak alt küme oluşturulur. Bu alt küme üzerinde yapılan değişiklik ana veri setini etkilemez.

In [97]:
m = np.random.randint(10,size=(5,5))
m

array([[2, 9, 6, 3, 9],
       [2, 3, 1, 1, 7],
       [1, 2, 9, 0, 5],
       [6, 0, 7, 3, 6],
       [2, 6, 1, 9, 1]])

In [99]:
alt_m = m[:3,:2].copy()
alt_m

array([[2, 9],
       [2, 3],
       [1, 2]])

In [100]:
alt_m[0,0]=9999
alt_m

array([[9999,    9],
       [   2,    3],
       [   1,    2]])

In [101]:
m

array([[2, 9, 6, 3, 9],
       [2, 3, 1, 1, 7],
       [1, 2, 9, 0, 5],
       [6, 0, 7, 3, 6],
       [2, 6, 1, 9, 1]])

## Fancy Index ile elemanlara erişmek

In [103]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [104]:
v[1]

3

In [105]:
v[3]

9

In [106]:
v[5]

15

In [107]:
[v[1],v[3],v[5]]

[3, 9, 15]

Yukarıda oluşturulmuş veri setinin 1.,3. ve 5. elemanlarına erişmek istediğimde yukarıdaki yöntemleri uygularım fakat bu veri seti daha da büyüdüğünde bunu yapmam zorlaşır. Bu durumlarda fancy index devreye girer. 

In [108]:
index = [1,3,5]
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [109]:
v[index]

array([ 3,  9, 15])

## İki boyutta fancy index

In [110]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [112]:
m[satir,sutun]

array([1, 5])

## Basit index ile fancy index

In [113]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
m[0,[1,2]]

array([1, 2])

## Slice ile fancy index

In [116]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu eleman işlemleri

In [117]:
v = np.array([1,2,3,4,5])

In [118]:
v<3

array([ True,  True, False, False, False])

In [119]:
v[v<3]

array([1, 2])

In [120]:
v[v>=3]

array([3, 4, 5])

In [121]:
v[v<=3]

array([1, 2, 3])

In [127]:
v[v != 3]

array([1, 2, 4, 5])

## Matematiksel İşlemler

In [123]:
v

array([1, 2, 3, 4, 5])

In [124]:
v*2

array([ 2,  4,  6,  8, 10])

In [125]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [126]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

Matematiksel işlemleri bu şekilde yaparken arkada NumPy kütüphanesinde çeşitli dönüşümler yapılır ve **ufunc**lar çalışır. Örneğin;
v-1 = np.subtract(v,1) 

In [128]:
v-1

array([0, 1, 2, 3, 4])

In [130]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [131]:
v+1

array([2, 3, 4, 5, 6])

In [132]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [133]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [134]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [135]:
np.power(v,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [136]:
v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [137]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [138]:
np.absolute(np.array([-3]))

array([3])

In [139]:
np.sin(360)

0.9589157234143065

In [140]:
np.cos(180)

-0.5984600690578581

In [141]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [142]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [143]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

## İstatistiksel Hesaplamalar 

In [144]:
v

array([1, 2, 3, 4, 5])

In [145]:
np.mean(v)

3.0

In [146]:
v.sum()

15

In [147]:
v.min()

1

In [148]:
v.max()

5

In [149]:
np.var(v)

2.0

In [152]:
np.std(v)

1.4142135623730951

## NumPy ile iki bilinmeyenli denklem çözümü

**5 * x0 + x1 = 12**

**x0 + 3 * x1 = 10**

In [154]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [155]:
a

array([[5, 1],
       [1, 3]])

In [156]:
b

array([12, 10])

In [157]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])